//! Owns tasks (Futures) and the ready queue. Polls tasks until done.
//! When nothing is ready, parks via the reactor.

use std::cell::RefCell;
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;
use std::task::{Context, Poll};
use crate::reactor::Reactor;
use crate::waker::{make_waker, ReadyQueue, TaskId};

/// A spawned task: a pinned, boxed Future returning ().
/// Pinned because Futures generated by async fn may hold internal self-references.
/// Boxed because we need a single concrete type to store many different Futures together.
type TaskFuture = Pin<Box<dyn Future<Output = ()>>>;

/// A handle tasks can hold to spawn new tasks.
#[derive(Clone)]
pub struct Spawner {
    pending: Rc<RefCell<Vec<TaskFuture>>>,
}

impl Spawner {
    pub fn spawn<F: Future<Output = ()> + 'static>(&self, fut: F) {
        self.pending.borrow_mut().push(Box::pin(fut));
    }
}

pub struct Executor {
    tasks: HashMap<TaskId, Rc<RefCell<TaskFuture>>>,
    ready: ReadyQueue,
    next_id: TaskId,
    reactor: Rc<Reactor>,
    pending: Rc<RefCell<Vec<TaskFuture>>>,
}

impl Executor {
    pub fn new(reactor: Rc<Reactor>) -> Self {
        Self {
            tasks: HashMap::new(),
            ready: Rc::new(RefCell::new(Vec::new())),
            next_id: 0,
            reactor,
            pending: Rc::new(RefCell::new(Vec::new())),
        }
    }

    pub fn spawner(&self) -> Spawner {
        Spawner { pending: self.pending.clone() }
    }

    /// Spawn a Future. Returns its task id.
    pub fn spawn<F: Future<Output = ()> + 'static>(&mut self, fut: F) -> TaskId {
        let id = self.next_id;
        self.next_id += 1;
        self.tasks.insert(id, Rc::new(RefCell::new(Box::pin(fut))));
        self.ready.borrow_mut().push(id);
        id
    }

    /// Move anything in `pending` into the live task set.
    fn drain_pending(&mut self) {
        let new_tasks: Vec<_> = self.pending.borrow_mut().drain(..).collect();
        for t in new_tasks {
            let id = self.next_id;
            self.next_id += 1;
            self.tasks.insert(id, Rc::new(RefCell::new(t)));
            self.ready.borrow_mut().push(id);
        }
    }

    pub fn run(&mut self) {
        loop {
            self.drain_pending();

            // Drain everything ready right now.
            loop {
                let id = match self.ready.borrow_mut().pop() {
                    Some(id) => id,
                    None => break,
                };

                // Build a std::task::Waker for this task, wrap it in a Context.
                let waker = make_waker(id, self.ready.clone());
                let mut cx = Context::from_waker(&waker);

                let task = match self.tasks.get(&id) {
                    Some(t) => t.clone(),
                    None => continue, // already finished
                };

                // Poll the Future. `.as_mut()` turns Pin<Box<...>> into Pin<&mut ...>.
                let result = task.borrow_mut().as_mut().poll(&mut cx);

                if matches!(result, Poll::Ready(())) {
                    self.tasks.remove(&id);
                }

                // The poll might have spawned new tasks — fold them in immediately.
                self.drain_pending();
            }

            if self.tasks.is_empty() {
                break;
            }

            // Nothing ready, tasks still alive → park on the reactor.
            self.reactor.wait();
        }
    }
}
